runtime: php73

handlers:
  - url: /(.+\.(gif|png|jpg|jpeg|pdf|asc))$
    static_files: \1
    upload: .+\.(gif|png|jpg|jpeg|pdf|asc)$
    secure: always
  - url: .*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 2
  max_idle_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
  min_pending_latency: 30ms
  max_pending_latency: 100ms