
<table border="0" cellspacing="0" cellpadding="0" align="left">
<tr height="99">
<td><img src="images/sf.jpg"></td>
<td width="607"><font size="+4"><?php echo $pagetext; ?></font></td>
</tr>
<tr>
<td valign="top"><br><br><br>
<a href="mail.php?com=list">Inbox</a><br><br>
<a href="compose.php">Compose New Mail</a><br><br>
<a href="logout.php">Logout</a><br><br>
<IMG src="http://sourceforge.net/sflogo.php?group_id=3155&amp;type=1" width="88" height="31" border="0"></a></td>
<td>
