<!-- START: /inc/footer.inc -->
</td>
<td bgcolor="#006699" width="130" valign="top" align="left">
<img src="/images/pixel.gif" width="130" height="2"><br>
<a href="#" onClick="javascript:OpenWindow('http://knowmusic.com/rooty/flash/intro_jus.html', '700', '500');"><img src="/images/library/basement_jaxx/banners/microsite_120x100.jpg" class="linked_img" alt="Basement Jaxx Microsite" width="120" height="100"></a>
<br>
<a href="#" onClick="javascript:OpenWindow('http://the-raft.com/mickjagger/jukebox/index_player_lo.html', '600', '450');"><img src="/images/library/mick_jagger/banners/jukebox_120x100.jpg" class="linked_img" alt="Mick Jagger Juke Box" width="120" height="100"></a>
</td>
</tr>
</table>

<br>

<CENTER>

<font size="1" face="verdana" color="#000000">

<a class="link_onFFFFFF" href="/" title="Home">Home</a>
|
<a class="link_onFFFFFF" href="/news/" title="News">News</a>
|
<a class="link_onFFFFFF" href="/reviews/" title="Reviews">Reviews</a>
|
<a class="link_onFFFFFF" href="/artists/" title="Artists">Artists</a>
|
<a class="link_onFFFFFF" href="/forums/" title="Forums">Forums</a>
|
<a class="link_onFFFFFF" href="/live/" title="Live">Live</a>
|
<a class="link_onFFFFFF" href="/au_vi/" title="Audio/Video">Audio/Video</a>
|
<a class="link_onFFFFFF" href="/interviews/" title="Interviews">Interviews</a>
<br>
<a class="link_onFFFFFF" href="/contactus/" title="Contact Us">Contact Us</a>
|
<a class="link_onFFFFFF" href="/advertising/" title="Advertising">Advertising</a>

</font>

<br><br>

<font size="1" face="verdana" color="#000000">&copy; 2000-1 <font size="1" face="verdana" color="#000000">Music Goes On</font></font>

</CENTER>

</body>
</html>
<!-- END: /inc/footer.inc -->