<!-- START: /inc/top.inc -->
<?php
$headline = $title;

echo "<table border=\"0\" cellpadding=\"5\" cellspacing=\"0\" width=\"100%\" style=\"table-layout:fixed\" align=\"center\" valign=\"top\">\n\n";
 echo "    <tr>\n";
 echo "        <td width=\"75%\" valign=\"top\" align=\"left\" bgcolor=\"#006699\"><font face=\"verdana\" size=\"1\" color=\"#FFFFFF\"><b>$headline</b><br>$subtitle</font></td>\n";
 if($columns==2)
 {
  echo "        <td width=\"25%\" valign=\"top\" align=\"right\" bgcolor=\"#006699\"><img src=\"/images/pixel.gif\" width=\"10\" height=\"10\"></td>\n";
 }
 echo "    </tr>\n";
 echo "    <tr>\n";
 echo "        <td width=\"75%\" valign=\"top\" align=\"left\" bgcolor=\"#f7f7f7\"><font face=\"verdana\" size=\"1\" color=\"#000000\"><p align=\"justify\">";
?>
<!-- END: /inc/top.inc -->