<? /* ANNIE@IT BEGIN */ ?>

<? $title = '<br><CENTER><img src="/images/features/annie-it_feb2001/logo_anniemiddle.gif" width="180" height="51"></CENTER>'; include("/home/mgo/musicgoeson-www/inc/top.php"); ?>

	<font size="2" face="verdana">
	<a href="/features/annie-it_feb2001/"><b><u>ANNIE@IT</u></b></a><br>
	</font>
	<font color="black" size="2" face="verdana">
	<b>Annie Nightingale</b>'s controversial and innovative new internet only chat show
	<i>ANNIE@IT</i> will hit your monitors on Monday February 5th. The seminal DJ and
	broadcaster who	has just been awarded an MBE in the New Years Honours list will be
	presenting the show that will be broadcast on Mondays and Fridays at 12.30pm
	(lunchtime, folks) on
	www.annieatit.com.  <a href="/features/annie-it_feb2001/">Click here</a> for more
	information and to see Annie's video intro.<br><br>
	</font>

<? include("/home/mgo/musicgoeson-www/inc/middle.php"); ?>

<? include("/home/mgo/musicgoeson-www/inc/bottom.php"); ?>

<? /* ANNIE@IT END */ ?>