<? /* ANNIE@IT BEGIN */ ?>

<? $title = '<br><CENTER><img src="/images/features/annie-it_feb2001/logo_anniemiddle.gif" width="180" height="51"><br>Kevin Shields</CENTER>'; include("/home/mgo/musicgoeson-www/inc/top.php"); ?>

	<font size="2" face="verdana">
	<a href="/features/annie-it_feb2001/annie-kevin.php"><b><u>ANNIE@IT - Kevin Shields</u></b></a><br>
	</font>
	<font color="black" size="2" face="verdana">
	Even though My Bloody Valentine hasn’t released anything since Loveless 8 years ago, Kevin
	Shields and his musical legacy based on ‘messing around with sounds’ hasn’t been forgotten. He
	now plays guitar with Primal Scream and if you thought, like Annie, that he was not a talker,
	you will be proved wrong here! Follow him on his early musical journey, from his early
	childhood in America to the present day. The trip will take you from Slade and The partridge
	Family to DAF and The Birthday Party via The Buzzcocks and Jesus and Mary Chain.
	Fascinating!
	</font>

<? include("/home/mgo/musicgoeson-www/inc/middle.php"); ?>

<? include("/home/mgo/musicgoeson-www/inc/bottom.php"); ?>

<? /* ANNIE@IT END */ ?>