<?php /* ASH PROMO BEGIN */ ?>

<?php $title = 'ASH COMPETITION'; include("/home/mgo/musicgoeson-www/inc/top.php"); ?>

	<img src="/images/features/ash_jan2001/col_185x123.jpg" width="185" height="123" align="left" border="1">

	<font size="2" face="verdana">
	<a href="/features/ash_jan2001/"><b><u>Win A Copy of Ash's New Single</u></b></a><br>
	</font>
	<font color="black" size="2" face="verdana">
	<i>Music Goes On</i> has got five copies of Ash's new single, Shining Light to give away.
	You can also download the track for FREE.
	</font>
	<br><br>

<?php include("/home/mgo/musicgoeson-www/inc/middle.php"); ?>

<?php include("/home/mgo/musicgoeson-www/inc/bottom.php"); ?>

<?php /* ASH PROMO END */ ?>